# AI Service Routing Rules
#
# This file is used by the LocalClientManager to configure selective proxying.
# It defines which domains and IPs should be routed through the Shadowsocks proxy.

routing_rules:
  version: "1.0"
  default_action: "direct"  # Traffic not matching rules goes "direct" (no proxy)
  
  # Domains that should use the Shadowsocks proxy
  proxy_domains:
    # OpenAI Services
    - "*.openai.com"
    - "api.openai.com"
    - "chat.openai.com"
    - "platform.openai.com"
    
    # Google AI Services  
    - "*.googleapis.com"
    - "ai.google.dev"
    - "makersuite.google.com"
    - "generativelanguage.googleapis.com"
    
    # Anthropic Services
    - "*.anthropic.com"
    - "api.anthropic.com"
    - "console.anthropic.com"
    
    # Additional AI Services (optional)
    - "*.cohere.ai"
    - "api.cohere.ai"
    - "*.huggingface.co"
    - "api-inference.huggingface.co"
    
  # IP ranges that should use the proxy (if needed)
  proxy_ips:
    - "23.102.140.112/28"  # Example OpenAI IP range
    
  # Domains that should NEVER use the proxy (explicit direct)
  direct_domains:
    - "*.apple.com"
    - "*.icloud.com"
    - "*.github.com"
    - "localhost"
    - "127.0.0.1"
    - "*.local"
    
  # Keywords in URLs that indicate AI API usage
  proxy_keywords:
    - "/v1/chat/completions"
    - "/v1/completions" 
    - "/v1/embeddings"
    - "/v1/images"
    - "/generate"
    - "/completions"

# PAC file generation settings
pac_settings:
  proxy_server: "SOCKS5 127.0.0.1:1080"
  fallback: "DIRECT"
  
# Application-specific routing settings
app_routing:
  curl:
    proxy_env: true  # Set HTTP_PROXY for curl commands
    
  python:
    proxy_env: true  # Set proxy for requests/urllib
    
  browsers:
    pac_file: true   # Use PAC file for browsers